
name: Build APK (Wilczek Glyph Toy)

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android platforms & build-tools
        run: |
          sdkmanager --install "platforms;android-35" "build-tools;35.0.0" "platform-tools"

      - name: Ensure libs dir and SDK AAR exists
        run: |
          test -f app/libs/glyph-matrix-sdk-1.0.aar || (echo "❌ Brak app/libs/glyph-matrix-sdk-1.0.aar — dodaj plik .aar z Glyph Matrix SDK" && exit 1)

      - name: Build Debug APK
        uses: gradle/gradle-build-action@v3
        with:
          arguments: assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/*.apk
